tutormfe/plugin.py
The openedx-mfe Docker image should be re-built by every user. If we push the
image to docker.io, people are at risk of actually downloading it, and it will
simply not work for them.
This is ready for review @overhangio/tutor-developers.
=> fix: don't push the mfe image to docker.io

README.rst
In particular, if the profile waffle flag is not deleted, it will result in 500
errors in the LMS.
This is ready for review @overhangio/tutor-developers.
=> docs: waffle flags need to be deleted after uninstall

tutormfe/patches/caddyfile, tutormfe/patches/nginx-extra
The MFE service was running directly behind Caddy, and not Nginx. Thus, when
Caddy was disabled (RUN_CADDY=false), the MFE service was unavailable. To
address this, we include nginx as an extra proxy between Caddy and the MFE.
Caddy should only take care of SSL termination, as for other services.
Close #6.
This is ready for review @overhangio/tutor-developers. Cc @insad who opened the initial PR: https://github.com/overhangio/tutor-mfe/pull/7
=> fix: MFE service unavailable behind custom host proxy

README.rst
If the ENABLE_PROFILE_MICROFRONTEND site configuration is not removed, the LMS
shows 500 errors everywhere.
This is ready for review @overhangio/tutor-developers.
=> docs: clarify profile MFE uninstallation

tutormfe/templates/mfe/build/mfe/Dockerfile
Enable npm packages override  for all MFEs.
See [thread](https://discuss.overhang.io/t/customise-mfes-branding/2029).
=> Enable npm packages override  for all MFEs

tutormfe/patches/caddyfile
This PR aims to fix a typo in an environment variable referenced in the caddyfile patch. IT should be `default_site_port` according to [this definition](https://github.com/overhangio/tutor/blob/72baae0e27379821652ee7db495708f9cb6396ff/tutor/templates/local/docker-compose.prod.yml#L11).
@regisb
=> fix: typo when calling default_site_port environment variable

tutormfe/plugin.py
The command `tutor images push mfe` was not working since `remote-image`
hook was not present in the mfe plugin. This PR adds the missing hook.
https://discuss.overhang.io/t/cant-push-custom-mfe-image-to-container-registry/2257
1. Without this PR, try to run `tutor images push mfe`, It will show the error - `Error: Image 'mfe' could not be found`.
1. Pull this PR and run `tutor images push mfe`, it will attempt to push the `mfe` image.
=> fix: missing remote-image hook

tutormfe/plugin.py, tutormfe/templates/mfe/build/mfe/Dockerfile
Currently openedx itself and mfe are using two different Caddy base images, which is not ideal. This PR fixes this.
=> avoid using two different Caddy base images

tutormfe/templates/mfe/build/mfe/env/development
This fixes the link to the studio that is displayed in the learning mfe in
every section.
=> fix: studio url in dev mode

tutormfe/templates/mfe/build/mfe/env/production
In bash, single quotes within single quotes cannot be escaped
directly. In particular, this doesn't work:
SITE_NAME='Kyle\'s "very cool" Open edX'
because the backslash is treated literally.
A workaround is actually to close the single-quoted string,
follow it with an escaped single quote, and then re-open a
new single quoted string. The following three lines
yield an identical, correctly-escaped SITE_NAME:
SITE_NAME='Kyle' + "\'" + 's "very cool" Open edX'
SITE_NAME='Kyle' + \' + 's "very cool" Open edX'
SITE_NAME='Kyle'\''s "very cool" Open edX'
This commit changes the envs/production template
to use such an escaping strategy.
This fix should allow `tutor images build mfe` to work
correctly when PLATFORM_NAME contains single quotes,
double quotes, or pieces of bash substitution syntax …
=> fix: further escape single quotes inside the platform name

README.rst
Using the example of `mfe_branding_plugin` caused the error below:
`Error: Invalid patches in plugin mfe-branding. Expected dict, got <class 'NoneType'>.`
it looks like you missed a couple of spaces before the patches.
it has been tested and it solve the issue.
=> indentation added to mfe plugin example

tutormfe/templates/mfe/build/mfe/Dockerfile
Additional requirements are required, and we cannot download the pact binary on
arm64: https://github.com/pact-foundation/pact-js-core/issues/264
Close #31.
=> fix: building mfe image on arm64

tutormfe/plugin.py
Learning-MFE won't view records button, unless the
ENABLE_LEARNER_RECORD_MFE is set to true.
This shall fixes: openedx/build-test-release-wg/issues/168
=> fix: Add env variable to enable records button in profile

README.rst, tutormfe/patches/local-docker-compose-dev-services, tutormfe/plugin.py
See individual commit messages.
Blocks https://github.com/overhangio/tutor/pull/644
=> feat: deprecate `runserver` in favor of `start`

tutormfe/templates/mfe/build/mfe/Dockerfile
This is faster and ensures that we install the pinned requirements from
`package-lock.json`.
=> feat: `npm ci` instead of `npm i`

tutormfe/templates/mfe/build/mfe/Dockerfile
Previously, build stages were ordered like this in the
rendered Dockerfile (dependencies in parenthases):
* base
* i18n        (base)
* app1-src    (base)
* app1-i18n   (base, app1-src)
* app1-dev    (base, app1-src, app1-i18n)
* app1        (app1-dev)
* app2-src    (base, app2-src)
* app2-i18n   (base, app2-src)
* app2-dev    (base, app2-src, app2-i18n)
* app2        (app2-dev)
* ...
* production  (app1, app2, ..., appN)
MFEs in dev mode only use the output of the *-dev stages.
However, because some of the *-dev stages came after
the intermediate production stages in the Dockerfile (app1, app2, etc),
Docker unnecessarily built the prod stages whenever `tutor dev start`
was run, which often forced users to wait through the prod-only
`npm run build`.
This commit reorders the build stages …
=> perf: re-order Dockerfile stages to significantly optimize build speed

tutormfe/templates/mfe/build/mfe/env/production
tutor-mfe set SITE_NAME env variable of mfe to equal
PLATFORM_NAME config value, however in case it has a space, this
would result SITE_NAME to be empty.
This change prefix space with \ as, i.e My Site becaomse
My\ Site.
Before this might not has been issued because all values were
wrapped with ' hence #56
To test this change (you have to be in production mode)
- Set your PLATFORM_NAME to any thing that incldues space
- Build the mfe image
- Check `document.title` in dev console of any mfe
- It will not incldue PLATFORM_NAME
After applying this patch, the last step above, should result
the PLATFORM_NAME i.e. "Learning | PLATFORM_NAME"
=> fix: escape space in platform name

tutormfe/templates/mfe/build/mfe/Dockerfile
**TL;DR -** Use the `NPM_REGISTRY` config in Dockerfile, the same way it's done in other Tutor Dockerfiles (tutor-discovery, tutor-ecommerce, tutor:openedx, tutor-contrib-credentials).
We just replace the default registry URL with the config `NPM_REGISTRY` which defaults to the same value.
This is required in order to use a custom registry either for caching or for accessing private packages.
**Testing**
I've been using that fix for a while. I'm currently surviving long repetitive downloads thanks to my local pull-through cache NPM registry powered by [Verdaccio](https://verdaccio.org/docs/what-is-verdaccio/).
FYI @arbrandes @regisb
=> Fix (build): use NPM_REGISTRY from the config

tutormfe/patches/local-docker-compose-dev-services
In the docker compose for development, the loopback IP address is hardcoded to 127.0.0.1. In some dev environments, e.g. in cloud environments like Cloud9, or in Windows WSL, the internal web server is accessed via a different IP address. Removing the 127.0.0.1 in the ports section will fix this problem.
Fixes #72
=> fix: Remove hardcoded loopback ip in dev docker-compose

tutormfe/patches/local-docker-compose-dev-services, tutormfe/templates/mfe/apps/mfe/webpack.dev-tutor.config.js, tutormfe/templates/mfe/build/mfe/Dockerfile
A small fix for issue #71 to avoid overwriting the local `webpack.dev.config.js` in MFEs with the plugin's version of the file mounted at container start
The MFEs targetted by this all have a local `webpack.dev.config.js`. Here are the ones branched for the olive release:
frontend-app-gradebook
frontend-app-publisher
frontend-app-ora-grading
frontend-app-communications
frontend-app-program-console
frontend-app-learner-dashboard
frontend-app-library-authoring
To account for the 2 possible cases for all MFEs, the fix was tested and confirmed to work with:
-  `frontend-app-gradebook` (using local config)
-  `frontend-app-learning` (using config resolved from `frontend-platform`)
The modification in `Dockerfile` won't trigger a long image rebuild as it affects only the last step (`CMD`).
My …
=> fix(dev): inherit local webpack.dev.config.js

tutormfe/templates/mfe/build/mfe/Dockerfile
Hi
I was reading MFE `Dockerfile` and noticed that the git package was mentioned twice in `apt install` level, so I removed the second one :)
I know it doesn't make any harm but, this way is cleaner, I guess.
=> fix: duplicate git package removed

tutormfe/templates/mfe/tasks/lms/init
Hi everyone
I noticed that deleting the user account doesn't work by default.
after a [little search](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/user_retire/service_setup.html#retirement-states), I found that we need to populate retirement states before deleting a user.
I've tested this and it worked after retirement states were populated.
this PR will add `populate_retirement_states` command if the Account MFE was selected.
=> Delete user account issue on Account MFE

tutormfe/patches/local-docker-compose-dev-services, tutormfe/templates/mfe/build/mfe/Dockerfile, tutormfe/templates/mfe/build/mfe/env/production
With this change, we avoid the problem of having to escape env variables altogether. Previously, env variables were loaded both by bash (in development) and docker-compose (in production). This meant that we had to deal with escaping in both contexts, which was the source of trouble. We resolve this by loading env vars only with bash.
Close #61.
=> fix: escape env variables

tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings
When introducing dynamic config[1], `CSRF_TOKEN_API_PATH` was removed from the MFE build environment and not added to the corresponding Django settings, leading to POST failures across the board.
This addresses the problem by adding `CSRF_TOKEN_API_PATH` back in.
[1] https://github.com/overhangio/tutor-mfe/pull/69
=> fix: add missing CSRF configuration

tutormfe/patches/local-docker-compose-prod-services
Since we no longer need the build context to pass in MFE configuration at runtime, by removing it from the `tutor local` docker-compose we can avoid rebuilding the image whenever a `start` is issued.
=> fix: Don't rebuild image on `local start`

tutormfe/patches/local-docker-compose-prod-services
Now that the mfe image is pushed to docker.io, there is no longer any need to re-build every time we run `tutor local start`.
=> feat: do not build mfe image on `local start`

README.rst
Issue:
- In README.rst, link to Authn and Discussions were given wrong
Fixed issue by correcting the links
=> fix: Incorrect Discussions and Authn links in README

README.rst
Added some missing code tags to readme which makes it a bit harder to read (markdown vs rst syntax)
=> fix: visual - missing code tags in Readme

README.rst
The MFE customization example does throw an exception as it is written right now. I've wrapped the two changes in a list and changed `add_item` to `add_items`.
=> Readme: Fix MFE customization example

LICENSE.txt, README.rst
This PR adds the AGPL 3.0 license file.
The licensing itself was already in the readme but the file was missing.
This fixes #115
=> chore: adding the license file as per the readme

tutormfe/templates/mfe/build/mfe/Dockerfile
Building the mfe Docker image on arm64 triggers the following error in the 'account-prod' stage:
Cannot find module 'imagemin-pngquant'
This was due to a missing system package.
I find it strange that no one reported this issue before, when there are plenty of users running macOS with arm64. I discovered this issue while setting up a multi-arch build CI environment.
=> fix: pngquant error during build on linux/arm64

tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings
frontend-component-header since version v.3.5 requires the
the settings of ACCOUNT_SETTINGS_URL to exists as it uses
it point to the account MFE.
- openedx/frontend-component-header/pull/210 PR that add the setting the componenet
- openedx/wg-build-test-release/issues/268 which this fixes
=> fix: Add account url in dynamic config

changelog.d/20230526_152532_regis.md, tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings
The "account" menu item could not be clicked in other MFEs, such as the profile.
This is a backport of another fix to Palm:
https://github.com/overhangio/tutor-mfe/pull/121
Close #128.
=> fix: "account" menu item from MFE menus

README.rst, changelog.d/20230623_101803_arbrandes_dockerfile_patches_per_mfe.md, tutormfe/templates/mfe/build/mfe/Dockerfile
This should allow managing individual MFE node_modules (such as installing custom dependencies for l10n purposes) without having to fork the corresponding upstream codebases.
=> feat: allow patching the Dockerfile per MFE

README.rst, changelog.d/20230627_090554_arbrandes_cache_invalidation.md, tutormfe/plugin.py, tutormfe/templates/mfe/build/mfe/Dockerfile
This will invalidate the image build cache for each MFE whenever:
1. A direct URL to the repository's branch refs is provided
and
2. The head of the branch being built changed between builds.
For Github, this is available via [1].  For Gitlab, via [2].
[1] https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference
[2] https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch
=> feat: invalidate build cache on upstream changes

changelog.d/20230628_084907_arbrandes_cache_invalidation_take_2.md, tutormfe/plugin.py
Picking up where https://github.com/overhangio/tutor-mfe/pull/131 left off.
=> fix: pick default GH refs API endpoint based on package version

changelog.d/20230802_123027_regis_fix_dev_profile_link.md, tutormfe/patches/openedx-lms-development-settings
In development, the link to the profile page was incorrect in the header bar of the learning MFE (and other MFEs) as well. Note that the link was correct in the dashboard.
=> fix: link to profile in dev

changelog.d/20230627_162842_regis.md, tutormfe/patches/k8s-deployments
We should use the default cluster value for imagePullPolicy. This makes
it easier to run the MFE with Minikube:
https://minikube.sigs.k8s.io/docs/handbook/pushing/
> Tip 1: Remember to turn off the imagePullPolicy:Always (use
> imagePullPolicy:IfNotPresent or imagePullPolicy:Never) in your yaml
> file. Otherwise Kubernetes won’t use your locally build image and it
> will pull from the network.
=> feat: don't override imagepullpolicy on k8s

README.rst, tutormfe/plugin.py
This will fix the following typos:
```
Assesments -> Assessments
opreators -> operators
```
=> chore: corrected typos

README.rst
This will fix the same issue we had in [tutor-xqueue](https://github.com/overhangio/tutor-xqueue/pull/19)
=> docs: square characters replaced with →

changelog.d/20231003_133500_dave_remove_trailing_slash.md, tutormfe/templates/mfe/build/mfe/Dockerfile
We previously generated the PUBLIC_PATH base for each MFE with a trailing slash, e.g. "/authn/". But the actual links that point to these from the LMS and Studio don't have a trailing slash in them, e.g. "/authn". This commit removes the trailing slash to be consistent.
=> fix: remove trailing slash from PUBLIC_PATH env var

changelog.d/20231002_172323_codewithemad_config_loaded_action.md, setup.py, tutormfe/plugin.py
As a part of https://github.com/overhangio/tutor/issues/557, we should warn the users if they're not following the apps.LMS_HOST pattern for the MFE_HOST.
This will introduce a new check to see if the MFE_HOST is a subdomain of LMS_HOST or not using the new [CONFIG_LOADED action](https://github.com/overhangio/tutor/pull/901) .
=> Fix: MFE_HOST check with the new CONFIG_LOADED action

tutormfe/patches/openedx-cms-development-settings, tutormfe/patches/openedx-cms-production-settings, tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings
We are going to upgrade to Django 4.2 for Quince.
Issue: https://github.com/openedx/wg-build-test-release/issues/315
PR to edx-platform: https://github.com/openedx/edx-platform/pull/33516 (will be merged only after Tutor preparation for Django4.2)
[Notes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3726802953/Pending+Release+Quince#Operational-%E2%9A%99%EF%B8%8F) about Django4.2 schema changes for CSRF_TRUSTED_ORIGINS.
This PR has been testing for Django 3.2 as well.
=> chore: update CSRF_TRUSTED_ORIGINS for Django 4.2

tutormfe/plugin.py
MFE images were not automatically built in nightly: this occurred both in local and dev mode.
Close #157
=> fix: auto-build images in nightly

tutormfe/templates/mfe/build/mfe/Dockerfile
Adds `atlas pull` to the Communications MFE. Support for other MFEs will come.
Here's a couple issues that needs to be tackled:
- Issue: How to enable the `atlas_pull` conditionally? 
* Old solution: `CORE_MFE_APPS` feature.
* Updated solution: Hard-coded `if app_name == communications`
- Issue: How to install `openedx-atlas` and `platform-frontend` which are required for `atlas pull`?
* Solution: In the package.json of the communications MFE.
- Issue: Should we use `make pull translations`? or hand-craft an `atlas pull` command?
* For discovery Regis recommended to avoid using make and writing an atlas command instead.
* For MFEs, it's better to use the Makefile step to allow each frontend to control its own plugins.
- Issue: After changing directory to `cd src/i18n/messages` the …
=> feat: add atlas pull for the communications app FC-0012

changelog.d/20231206_170625_regis_get_mfe.md, tutormfe/patches/openedx-cms-development-settings, tutormfe/patches/openedx-cms-production-settings, tutormfe/patches/openedx-lms-common-settings, tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings, tutormfe/plugin.py
Currently, the syntax to fetch mfe settings inside patches is very awkward:
{% for app_name, app in iter_mfes() %}
{% if app_name == "mymfe" %}
...
{% endif %}
{% endfor %}
We introduce a new template function to make this easier:
SOMETHING = "{{ get_mfe('mymfe')['port'] }}"
`get_mfe` is cached for performance.
=> feat: `get_mfe` template function

changelog.d/20231206_183103_arbrandes_fix_trailing_slash.md, tutormfe/templates/mfe/build/mfe/Dockerfile
This reverts ae60b2db08ef77a5dfb42b0ec9c2671c59af08a7.  We depend heavily on Webpack's `publicPath` for everything to work in MFEs that are hosted in sub-paths.  This variable affects many things, including URLs that are automatically generated for things like static assets or lazily loaded chunks of code.  If the trailing slash is not appended to, say, `/learning`, a React.lazy() will try to fetch this from Caddy, and fail:
`/learning210.3f8d0b2a9dbf3b1f1e69.js`
While this can (and probably should) be dealt with in frontend-platform, we do it here for now.
=> fix: append trailing slash to PUBLIC_PATH

changelog.d/20231208_142032_arbrandes_nightly.md, tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings, tutormfe/templates/mfe/tasks/lms/init
This is a new potential headliner for Quince.  With this, learners get the ability to start discussions on a sidebar to the right of any unit.  Like so:
After this patch, any new course gets this.
Old courses need manual configuration.  For one, the `edX (new)` provider needs to be selected in the Discussions configuration, in the course's "Pages and Resources":
There's also some neat additional configuration, either for new or old courses:
=> feat: Enable the new discussion sidebar in the Learning MFE

changelog.d/20231208_132545_mpwheel_mfe_dev_ports.md, tutormfe/patches/local-docker-compose-dev-services
Seems like the `PORT` environment variable was removed at some point after [v14.0.2](https://github.com/overhangio/tutor-mfe/blob/v14.0.2/tutormfe/patches/local-docker-compose-dev-services). This left development containers listening at the default port 8080, which is not forwarded to the host.
=> fix: specify port for dev server to listen on

CHANGELOG.md
This stems from this online conversations:
https://discuss.openedx.org/t/rebuilding-mfes-with-a-custom-fork/11918
=> docs: mention git repo extension in changelog

README.rst, changelog.d/20231212_131405_danyal.faheem_document_mfe_patches_catalog.md
**Changes**
- Added a catalog which includes every patch available for tutor-mfe in the README.
- Also included a one liner description of each patch for users to understand.
Fixes this [issue.](https://github.com/overhangio/tutor-mfe/issues/168)
=> docs: document mfe patches catalog

README.rst, changelog.d/20231220_054305_moisesgsalas.add_docker_final_patch.md, tutormfe/templates/mfe/build/mfe/Dockerfile
The `mfe-dockerfile-production-final` patch allows you to add instructions to the end of the final layer. This is useful in the case you want to override the default CMD or ENTRYPOINT instructions.
I think the patch will be useful overall, but my use case is as follows:
I've been exploring the idea of pointing [`Public Path`](https://webpack.js.org/guides/public-path/) to a cloudfront endpoint to speed up the MFE asset delivery. The only problem is that I can't reuse the image between environments because the cloudfront endpoint is hardcoded at build time. What I've been playing around is to use a placeholder string as the  `PUBLIC_PATH` and run a startup script in the container that replaces the placeholder with a value set in an environment variable.
=> feat: add patch at the end of the production layer

README.rst
As of Tutor v17 (Quince release) custom MFE plugins only accept URLs ending in `.git`. Providing a normal URL of the repository will cause failure in the build of MFE image when running `tutor images build mfe` as the custom MFE won't get cloned. 
This issue was previously mentioned [in this topic](https://discuss.openedx.org/t/rebuilding-mfes-with-a-custom-fork/11918) and the changelog was updated in [this PR](https://github.com/overhangio/tutor-mfe/pull/178). This PR updates the readme.
Closes https://github.com/overhangio/tutor-mfe/issues/180
=> docs: add warning to adding new MFEs section of the README about the MFE plugin URL ending in .git

changelog.d/20240213_141934_danyal.faheem_fix_course_authoring_mfe_removal.md, tutormfe/patches/openedx-cms-development-settings
Fixes #189.
Added a small check to make sure `course-authoring` is in the `MFE_APPS` before changing the settings.
=> fix: allow removal of course-authoring mfe

.gitlab-ci.yml, changelog.d/20240221_114505_danyal.faheem_add_learner_dashboard_dev_to_ci.md
Fixes #188. 
Added the `learner-dashboard-dev` image to the gitlab-ci so it can be pushed to the overhangio dockerhub repository.
=> ci: add learner-dashbaord-dev image

changelog.d/20240220_180043_hina.khadim_mfe_url_issue.md, tutormfe/patches/caddyfile
This PR resolves the #185 . The MFE_HOST url without any MFE name in url redirects to the LMS_HOST url. Before it, the MFE_HOST responds with 204.
=> fix: Issue MFE_HOST url redirects to LMS_HOST 

README.rst, changelog.d/20240202_172501_i_atlas_for_all.md, tutormfe/templates/mfe/build/mfe/Dockerfile
- Enable `atlas pull` for all MFEs
This pull request will fail unless the following PRs are merged:
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
=> feat: enable `atlas pull` for all MFEs | FC-0012

changelog.d/20240206_100528_arbrandes_fix_dev_runtime_config.md, tutormfe/templates/mfe/apps/mfe/webpack.dev-tutor.config.js
MFE runtime configuration in dev mode was not working properly prior to this.  It would always end up querying the `example.com` site configuration.  With this change, we force the request origin to always be the LMS host and port, as opposed to something like `apps.local.edly.io:2001`, which would trip up the Django site detection.
To reproduce (and test) the problem:
1. Check out an MFE locally.  For instance, the learner dashboard: `git clone https://github.com/openedx/frontend-app-learner-dashboard`
2. Configure a local mount for the MFE.  `tutor mounts add ./frontend-app-learner-dashboard`
3. Launch Tutor in dev mode: `tutor dev launch`.  (This should rebuild the appropriate images.)
4. Go to the site configuration admin page …
=> fix: Runtime config in dev mode

changelog.d/20240228_111818_arbrandes_nightly.md, tutormfe/templates/mfe/apps/mfe/webpack.dev-tutor.config.js
Only affects master development builds, so should go into nightly.  See openedx/axim-engineering#23.
=> fix: dev mode after frontend-build namespace change

changelog.d/20240301_160746_romulo_add_course_authoring_url_mfe_config.md, tutormfe/patches/openedx-lms-development-settings, tutormfe/patches/openedx-lms-production-settings
This PR adds the "COURSE_AUTHORING_MFE_BASE_URL" to the mfe config pointing to the Course Authoring MFE address.
We are rendering a course authoring URL in an iFrame inside the library authoring as part of the Tagging Project, so we need to know the Course Authoring MFE address.
- https://github.com/openedx/frontend-app-library-authoring/pull/400
=> feat: add course authoring mfe base url to mfe config

changelog.d/20240305_113936_moises.gonzalez_fix_dev_settings_rendering.md, tutormfe/patches/openedx-lms-development-settings
The `openedx-lms-development-settings` was missing the closing braces and caused an error when rendering.
=> fix: add missing curly braces

README.rst
I've been having to address this often enough that we should document it somewhere more obvious.
=> docs: How to reduce resource usage during MFE image rebuild

.github/workflows/sync.yml, .github/workflows/test.yml
More info can be found here:
https://github.com/overhangio/tutor-mfe/issues/192
=> chore: update CI workflow to Python 3.12

README.rst, tutormfe/templates/mfe/apps/mfe/webpack.dev-tutor.config.js
This will clean up the README and fix a typo in the `webpack.dev-tutor.config.js` file.
=> chore: cleanup

README.rst, tutormfe/templates/mfe/apps/mfe/webpack.dev-tutor.config.js
Backporting https://github.com/overhangio/tutor-mfe/pull/204 to nightly. Some merge conflicts in Readme (due to atlas changes) required manual fixups.
=> chore: docs cleanup

tutormfe/templates/mfe/tasks/lms/init
Adding optional toggle for redwood release, that is disabled by default for enhanced discoverability.
**Waffle toggles:** `courseware.enable_navigation_sidebar`, `courseware.always_open_auxiliary_sidebar`
For more information refer to **What should be off by default, BUT include clear documentation on how-to enable?** section in https://github.com/openedx/platform-roadmap/issues/357
=> feat: add new learning mfe toggles for navigation sidebar

tutormfe/templates/mfe/tasks/lms/init
This PR adding a missing waffle flag for the new studio Updates page.
The removal of this flag was already introduced in the https://github.com/overhangio/tutor-mfe/pull/208
The product ticket https://github.com/openedx/platform-roadmap/issues/357
=> fix: create waffle flag for new studio updates page on init

README.rst
This PR adds a missing space for the python code block directive so the code blocks are rendered correctly in the docs:
Before:
After:
=> fix: add missing space in python code block directive

README.rst, changelog.d/20240614_162207_regis_patch_dockerfile_common.md, tutormfe/templates/mfe/build/mfe/Dockerfile
This patch allows the customisation of the mfe base layer. Without it, we have to apply changes to the "mfe-dockerfile-pre-npm-install" patch, and that means re-apply changes for every single MFE.
=> feat: introduce a patch for the Docker base layer

changelog.d/20240621_123709_rediris_customize_dev_docker_image_tag.md, tutormfe/patches/local-docker-compose-dev-services, tutormfe/plugin.py
Introduces a `MFE_DOCKER_IMAGE_DEV_PREFIX` setting to customize dev MFE image docker repos. See discussion below for the benefits.
=> feat: introduces MFE_DOCKER_IMAGE_DEV_PREFIX

changelog.d/20240726_181354_regis_faster_init.md, tutormfe/templates/mfe/tasks/lms/init
Calling `./manage.py lms waffle_flag --list` so many times causes the MFE initialisation step to take a very long time, because `./manage.py lms` is very slow. We avoid this by listing existing waffle flags in a temporary file.
On an already initialized system, `tutor local do init --limit=mfe`
drops from 3min 27s to 25s.
=> feat: faster init by avoiding repeated waffle flag listing

changelog.d/20241010_090821_arbrandes_node_20_upgrade.md, tutormfe/templates/mfe/build/mfe/Dockerfile
As per https://github.com/openedx/public-engineering/issues/267, all Tutor-supported MFEs now work on Node 20, so we're good to switch to the Node 20 image.
Fixes #198
=> node 20 upgrade

README.rst, changelog.d/20241111_172451_arbrandes_frontend_plugin_support.md, tutormfe/hooks.py, tutormfe/plugin.py, tutormfe/templates/mfe/build/mfe/Dockerfile, tutormfe/templates/mfe/build/mfe/env.config.jsx
This provides a mechanism to configure frontend plugins using a new PLUGIN_SLOTS filter and a series of patches that modify a base `env.config.jsx`, in such a way that multiple plugins can take advantage of the file (including for purposes beyond frontend plugins) without clobbering each other.
(This is the third take.  Prior: #233, #234)
=> feat: support frontend plugins via env.config.jsx

changelog.d/20250226_134324_ahmed.khalid_mfe_ports_bug.md, tutormfe/patches/local-docker-compose-dev-services, tutormfe/plugin.py
The issue occurs when all MFEs (Micro Frontends) are mounted, and the `ports` section in the Docker configuration is left empty, leading to a syntax error in the generated Dockerfile. Specifically, the `ports:` line becomes invalid as another key follows it (`auth:`) without any content. In the `tutor dev` context, the issue occurs because developers mount MFEs for testing purposes. It won't reproduce for `tutor local`.
```
...
mfe:
ports:
auth:
....
```
- Clone all MFEs (`authn, account, communications, course-authoring, discussions, gradebook, learner-dashboard, learning, ora-grading, profile`)
- Run `tutor mounts add $(pwd)/frontend-app-*` where `*` represents all MFEs name one by one
- `tutor config save`
- `tutor dev start` OR directly check the `mfe-ports` section in …
=> fix: render mfe-ports for  unmounted mfes when these exist

changelog.d/20250324_232034_danyal.faheem_remove_site_configuration_script.md, tutormfe/templates/mfe/tasks/lms/init
Fixes part of https://github.com/overhangio/tutor/issues/1207.
As the site-configuration script is planned for deprecation in tutor-core, we look to remove or update its usage with a suitable replacement.
However, as of https://github.com/openedx/edx-platform/pull/36219, we do not require the site-configuration entries for the profile MFE anymore as the MFE is the default frontend going forward.
Similarly, the `redirect_to_microfrontend` flags are also not required anymore for the account and profile MFE as they are now the default frontends going forward.
=> chore: remove unnecessary settings and waffle flags for account and profile MFEs

tutormfe/templates/mfe/build/mfe/env.config.jsx
Edly recently faced an issue with Teak sandbox in which env.config.jsx did not apply when both Indigo and Aspects plugins were enabled. Upon debugging, it was found that there was an issue in env.config.jsx related patches in Indigo which caused this. However, it was not apparent at first that this was the issue and it required debugging and re-building images to pinpoint the issue. While we are fixing the Indigo issue in https://github.com/overhangio/tutor-indigo/pull/148, we are adding a small change in tutor-mfe to log the error in env.config.jsx if config fails to apply for any reason. This will make future debugging easier.
=> chore: add console error logging in env.config.jsx template
